crudclass/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = ([
    path("admin/", admin.site.urls),
    path("", include("web.urls", namespace="web")),
]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

)

admin.site.site_header = "CRUDclass Administration"
admin.site.site_title = "CRUDclass Admin Portal"
admin.site.index_title = "Welcome to CRUDclass Admin Portal"

web/urls.py
from django.urls import path
from .import views

app_name = "web"

urlpatterns = [
   path('',views.IndexView.as_view(),name='index'),
   path('add/',views.AddView.as_view(),name='add'),
   path('posts/',views.PostView.as_view(),name='posts'),
   path('<slug:slug>/',views.SingleView.as_view(),name='single'),
   path('edit/<int:pk>/',views.EditView.as_view(),name='edit'),
   path('delete/<int:pk>/',views.Delete.as_view(),name='delete'),

]

web/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.utils import timezone
# Create your models here.


class Core(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField(null=True)
    author = models.ForeignKey(User,on_delete=models.CASCADE, related_name='core')
    slug = models.SlugField(max_length=200, unique=True)
    updated = models.DateTimeField(auto_now=True)
    published  = models.DateTimeField(default=timezone.now)


    def get_absolute_url(self):
        return reverse('web:single', args=[self.slug])
    
    class Meta:
        ordering = ['-published']

    
    def __str__(self):
        return str(self.title)

web/forms.py
from django import forms
from .models import Core


class PostForm(forms.ModelForm):
    class Meta:
        model =  Core
        fields = "__all__"

web/views.py
from django.shortcuts import render
from .models  import Core
from django.views.generic import ListView, DetailView,CreateView, TemplateView,UpdateView,DeleteView
from django.urls import reverse_lazy
# Create your views here.

class IndexView(ListView):
    model = Core
    template_name = 'web/index.html'
    context_object_name = 'blog'


class SingleView(DetailView):
    model= Core
    template_name = 'web/single.html'
    context_object_name = 'post'


class PostView(ListView):
    model = Core
    template_name = 'web/posts.html'
    context_object_name = 'post_list'


class AddView(CreateView):
    model = Core
    
    template_name = 'web/add.html'
    fields = '__all__'
    success_url = reverse_lazy('web:posts')
    
class EditView(UpdateView):
    model = Core
    template_name = 'web/edit.html'
    fields = '__all__'
    pk_url_kwarg = 'pk'
    success_url = reverse_lazy('web:posts')

class Delete(DeleteView):
    model = Core
    pk_url_kwarg = 'pk'
    success_url = reverse_lazy('web:posts')
    template_name = 'web/confirm-delete.html'

templates/web/add.html
{% extends 'web/base.html' %} 
{% load static %} 
{% load widget_tweaks %}
{% block content %}


<div class="container pt-5">
    <form method="POST" novalidate>
        {% csrf_token %}
        {% for field in form.visible_fields %}  
        <div class="form-group">

            <label for="{{ field.id_for_label }}">{{ field.label }}</label>  
            {{ field|add_class:'form-control' }}
            {% for error in field.errors %}  
            <span class="help-block">{{error}}</span>
            {% endfor %}


        </div>
       {% endfor %}
       <div class="form-group">
        <button type="submit" class="btn btn-success"><span class="glyphicon glyphicon-ok"></span>Edit</button>
        
        <a href="{% url 'web:posts' %}" class="btn btn-primary">Cancel</a>
        
        </div>


    </form>

</div>







{% endblock %}

templates/web/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>CRUD</title>
  </head>
  <body>
    

    {% include 'web/header.html' %}

    {% block content %}
    {% endblock %}

    {% include 'web/footer.html' %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

templates/web/confirm-delete.html
{% extends 'web/base.html' %} 
{% load static %} 

{% block content %}


<div class="container  pt-5 pb-5">

    <form method="post">
        {% csrf_token %}
        <p>Are you sure want to delete "{{ object }}"?</p>
        <input type="submit" value="Confirm" >
    </form>

</div>


{% endblock %}

templates/web/edit.html
{% extends 'web/base.html' %} 
{% load static %} 
{% load widget_tweaks %}
{% block content %}

<div class="container pt-5" >
    <h2>Edit Post Here >>> </h2>
    </div>
    

<div class="container pt-5 pb-5">
    <form method="POST" novalidate>
        {% csrf_token %}
        {% for field in form.visible_fields %}  
        <div class="form-group">

            <label for="{{ field.id_for_label }}">{{ field.label }}</label>  
            {{ field|add_class:'form-control' }}
            {% for error in field.errors %}  
            <span class="help-block">{{error}}</span>
            {% endfor %}


        </div>
       {% endfor %}
       <div class="form-group pt-2">
        <button type="submit" class="btn btn-success"><span class="glyphicon glyphicon-ok"></span>Update</button>
        
        <a href="{% url 'web:posts' %}" class="btn btn-primary">Cancel</a>
        
        </div>


    </form>

</div>



{% endblock %}

templates/web/footer.html
{% load static %}



<!-- Footer -->
<footer class="bg-dark text-center text-white">
    <!-- Grid container -->
    <div class="container p-4">
    
  
      <!-- Section: Form -->
      <section class="">
        <form action="">
          <!--Grid row-->
          <div class="row d-flex justify-content-center">
            <!--Grid column-->
            <div class="col-auto">
              <p class="pt-2">
                <strong>Sign up for our newsletter</strong>
              </p>
            </div>
            <!--Grid column-->
  
            <!--Grid column-->
            <div class="col-md-5 col-12">
              <!-- Email input -->
              <div class="form-outline form-white mb-4">
                <input type="email" id="form5Example21" class="form-control " placeholder="Email Address" />
               
              </div>
            </div>
            <!--Grid column-->
  
            <!--Grid column-->
            <div class="col-auto">
              <!-- Submit button -->
              <button type="submit" class="btn btn-outline-light mb-4">
                Subscribe
              </button>
            </div>
            <!--Grid column-->
          </div>
          <!--Grid row-->
        </form>
      </section>
      <!-- Section: Form -->
  
      <!-- Section: Text -->
      <section class="mb-4">
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt distinctio earum
          repellat quaerat voluptatibus placeat nam, commodi optio pariatur est quia magnam
          eum harum corrupti dicta, aliquam sequi voluptate quas.
        </p>
      </section>
      <!-- Section: Text -->
  
     
    </div>
    <!-- Grid container -->
  
    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
      © 2023 Copyright:
      <a class="text-white" href="">developed by h4rshhin</a>
    </div>
    <!-- Copyright -->
  </footer>
  <!-- Footer -->

templates/web/header.html
{% load static %}

<header>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'web:index' %}">Postmania</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'web:posts' %}">Manage Posts</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'web:add' %}">Add New Post</a>
              </li>
              
              
            </ul>
           
          </div>
        </div>
      </nav>


</header>

templates/web/index.html
{% extends 'web/base.html' %} 
{% load static %} 
{% block content %}


<div class="container px-4 pt-5 pb-5">
    <div class="row gx-5">
        {% for blogs in blog %}
      <div class="col-4">
        <div class="card" style="width: 18rem;">
            <img src="https://via.placeholder.com/150x100" class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title" style="color: brown;">{{blogs.title}}</h5>
              <p class="card-text">{{blogs.content}}</p>
              <p class="card-text" style="color: rgb(0, 36, 238);">Published on : {{blogs.published}}</p>
              <a href="{{blogs.get_absolute_url}}" class="btn btn-primary">View More</a>
              <a href="{% url 'web:edit' blogs.pk %}" class="btn btn-success">Edit</a>
              <a href="{% url 'web:delete' blogs.pk %}" class="btn btn-danger">Delete</a>
            </div>

            <div class="card-footer">
                <small class="text-muted">Last updated {{blogs.updated}}</small>
            </div>

        </div>
      </div>
      {% endfor %}
      
      
    </div>
  </div>




{% endblock %}

templates/web/posts.html
{% extends 'web/base.html' %} 
{% load static %} 
{% block content %}

<h2 class="p-5" style="color: rgb(0, 0, 0);">Manage All Posts >>></h2>
<div class="container px-4 pt-5 pb-5">
    <div class="row gx-5">
        {% for blogs in post_list %}
      <div class="col-4">
        <div class="card" style="width: 18rem;">
            <img src="https://via.placeholder.com/150x100" class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title" style="color: brown;">{{blogs.title}}</h5>
              <p class="card-text">{{blogs.content}}</p>
              <p class="card-text" style="color: rgb(0, 36, 238);">Published on : {{blogs.published}}</p>
              <a href="{{blogs.get_absolute_url}}" class="btn btn-primary">View More</a>
              <a href="{% url 'web:edit' blogs.pk %}" class="btn btn-success">Edit</a>
              <a href="{% url 'web:delete' blogs.pk %}" class="btn btn-danger">Delete</a>

            </div>

            <div class="card-footer">
                <small class="text-muted">Last updated {{blogs.updated}}</small>
            </div>

        </div>
      </div>
      {% endfor %}
      
      
    </div>
  </div>




{% endblock %}

templates/web/single.html
{% extends 'web/base.html' %} 
{% load static %} 
{% block content %}


<div class="container pt-5 pb-5">
    <div class="card">
        <div class="card-header" style="color: brown;">
            {{post.title}}
        </div>
        <div class="card-body">
            <img src="https://via.placeholder.com/150x100" class="card-img-top" alt="..." style="width: 18rem;"> 
          <h5 class="card-title pt-2">{{post.title}}</h5>
          <p class="card-text">{{post.content}}</p>
          <p class="card-text">Author : {{post.author}}</p>
          <p class="card-text">Post Updated on{{post.updated}}</p>
          <p class="card-text">Post Published on{{post.published}}</p>
          
          <a href="{% url 'web:edit' post.pk %}" class="btn btn-success">Edit</a>
          <a href="{% url 'web:delete' post.pk %}" class="btn btn-danger">Delete</a>
        </div>
      </div>



</div>









{% endblock %}